### ISSUE TITLE
Issue: First animation is still running. 

### ISSUE THREAD

**Issue by hczhang** [siriscac/RippleView#15]
When I changed the animation duration of the ACTION_DOWN from 400 to 4000, the animation will keep showing on the screen after the animation triggered by the ACTION_UP stops.

**Comment by LostDemo** [comment]
Touch the button and slide out Effect of touch on the button
This is a bug?

**Comment by LostDemo** [comment]
Specific situation is the button in the slide page will appear only when the above problems
Solution to Cancel event handling
